language: cpp
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
env:
  global:
    - CONDA_PY=35
    - TRAVIS_PYTHON_VERSION=3.5
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: 
        - CXX=g++-4.9
        - CC=gcc-4.9
    - os: osx
      env:
        - CXX=clang++
        - CC=clang
install:
  - .travis/install.sh
script:
  - .travis/script.sh
after_failure:
  - .travis/after_failure.sh
after_success:
  - .travis/after_success.sh
