language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
matrix:
  include:
    - os: linux
      python: 3.5
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5 
install:
  - dpkg -l | grep libc6
  - source .travis/install.sh
script:
  - .travis/script.sh
after_success:
  - .travis/after_success.sh
