name: hdtconnector-test
channels:
  - ptorrestr
  - conda-forge
  - salford_systems
  - pkgw
dependencies:
  - python=3.5
  - setuptools
  - pyyaml
  - pytest
  - boost1-gcc5
  - zlib
  - bzip2
  - gcc-5         #[not osx]
  - hdtcpp
