package:
  name: hdtconnector
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
source:
  path: ../
requirements:
  build:
    - python
    - setuptools
    - zlib
    - bzip2
    - hdtcpp
    - boost
  run:
    - python
    - zlib
    - bzip2
    - hdtcpp
    - boost
test:
  source_files:
    - etc
    - hdtconnector/tests
  requires:
    - pytest
  commands:
    - pytest
about:
  home: https://github.com/ptorrestr/hdtconnector
  license: GPLv3
