package:
  name: hdtconnector
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
source:
  path: ../
requirements:
  build:
    - python
    - setuptools
    - zlib
    - bzip2
    - hdtcpp
  run:
    - python
    - zlib
    - bzip2
    - hdtcpp
test:
  source_files:
    - etc
    - hdtconnector/tests
  requires:
    - pytest
  commands:
    - folder=$(pwd)/../_t_env
    - DYLD_LIBRARY_PATH=$folder/lib otool -L $folder/lib/python3.5/site-packages/hdtconnector/libhdtconnector.so
    - DYLD_PRINT_LIBRARIES=1 DYLD_LIBRARY_PATH=$folder/lib pytest
about:
  home: https://github.com/ptorrestr/hdtconnector
  license: GPLv3
